#!/usr/bin/env node
// node scripts/build-edge.mjs [--check]
//
// Bundles the clx-edge worker (edge/worker.ts) into edge/bundle.gen.ts — the code clx.cx uploads
// into users' accounts, with its sha256 and compatibility date (docs/spec.md §4). The generated
// file is committed, so a review sees every change to what users run; edge/released.json lists the
// sha256 of every bundle ever committed — the scripts clx may treat as its own. `--check` fails if
// the committed file is not what the source builds to (tests and deploy run it).
import fs from 'node:fs';
import { createHash } from 'node:crypto';
import { build } from 'esbuild';

const OUT = 'edge/bundle.gen.ts';
const RELEASED = 'edge/released.json';
const COMPATIBILITY_DATE = '2026-09-01';

export async function buildEdge() {
  const r = await build({
    entryPoints: ['edge/worker.ts'],
    bundle: true,
    format: 'esm',
    target: 'es2022',
    platform: 'neutral',
    write: false,
    legalComments: 'none',
    charset: 'utf8',
    logLevel: 'warning',
  });
  const code = r.outputFiles[0].text;
  const sha256 = createHash('sha256').update(code).digest('hex');
  const file = [
    '// Generated by scripts/build-edge.mjs from edge/worker.ts — do not edit (docs/spec.md §4).',
    `export const EDGE_SHA256 = '${sha256}';`,
    `export const EDGE_COMPATIBILITY_DATE = '${COMPATIBILITY_DATE}';`,
    `export const EDGE_CODE = ${JSON.stringify(code)};`,
    '',
  ].join('\n');
  return { code, sha256, file };
}

if (process.argv[1]?.replace(/\\/gu, '/').endsWith('scripts/build-edge.mjs')) {
  const { sha256, file } = await buildEdge();
  const released = fs.existsSync(RELEASED) ? JSON.parse(fs.readFileSync(RELEASED, 'utf8')) : [];
  if (process.argv.includes('--check')) {
    const committed = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
    if (committed !== file) throw new Error(`${OUT} is stale: run node scripts/build-edge.mjs`);
    if (!released.includes(sha256)) throw new Error(`${RELEASED} lacks ${sha256}: run node scripts/build-edge.mjs`);
    console.log(`clx-edge ${sha256.slice(0, 12)} is current`);
  } else {
    fs.writeFileSync(OUT, file);
    if (!released.includes(sha256)) fs.writeFileSync(RELEASED, `${JSON.stringify([...released, sha256], null, 2)}\n`);
    console.log(`${OUT}: clx-edge ${sha256.slice(0, 12)}`);
  }
}
